### ISSUE TITLE
Can not sort all tabs

### ISSUE THREAD

**Issue by EddyMI3d** [jneilliii/OctoPrint-TabOrder#1]
Hello!
Neat idea with the tab sorting, but I only can sort the "build in" tabs, not the ones that were added with additional plugins, like Print History, Enclosure Plugin, Printer Stats...

Also the subtitle of the Tab Order plugin in the plugin list is a bit weird:
[http://www.eddymi3d.de/Images/OP_TO.jpg](url)

**Comment by zoombahh** [comment]
are you sure about this? i can reoder plugin tabs just fine. but you need to find the correct string, as it would appear in the config.yaml file if edited manually.

it seems plugin-tabs are prefixed with "plugin_". for me adding "plugin_printhistory" to the order worked a treat.

![werks](https://user-images.githubusercontent.com/1749138/35286694-feedb482-0060-11e8-9b2d-9de9ddc524ad.png)

**Comment by EddyMI3d** [comment]
Yes, I'm sure - otherwise I would not have written here ...

**Comment by jneilliii** [comment]
Which specific plugin are you trying to sort?  Like @zoombahh stated, you can sort plugin tabs, you just have to know the right string to use.

**Comment by jneilliii** [comment]
@EddyMI3d, did you CTRL+REFRESH to reload the local cache?  I think that might be your issue.  Like @zoombahh I just installed the print history tab and the string he used for that works perfect for me as well.

![image](https://user-images.githubusercontent.com/5249455/35307619-87f84264-0071-11e8-8f8d-08bc474f8cef.png)

**Comment by EddyMI3d** [comment]
I did CTRL+REFRESH, I did restart OctoPrint, I did a complete reset...

Also the subtitle of the Tab Order plugin in the plugin list is still a bit weird:

![op_to](https://user-images.githubusercontent.com/8533327/35326550-527bfe9c-00f7-11e8-9222-2fdf31dd2a44.png)

**Comment by zoombahh** [comment]
I did look at your image, but that was just the plugin description which jneilliii changed to
"Simple plugin to allow reordering of tabs within OctoPrint" in commit no 0.2.0 ( 8b46181a3b7de1e1933c584ae51a64ce26d774b8 )

maybe you could post a screenshot of your configuration ? the only pitfall ive run in to so far was "ctrl+r" does not clear browser cache, ctrl+f5 and ctrl+*click on refresh button* did clear the cache for me (using chromium, under windows)

if nothing else helps you could try opening debug tools (F12), going to the "network" tab and checking the "disable cache" checkbox, then reload the octoprint page

**Comment by EddyMI3d** [comment]
At least CRTL+F5 did it.
Thanks alot!

**Comment by jneilliii** [comment]
I'll update the pop up message to include the instructions for CTRL+F5. Release 0.2.0 fixed the plugin manager description.

**Comment by xhorntail** [comment]
As I sheepishly posted the same question and was referred to the only other existing question on this project, I figured I'd contribute my findings.

Everything works as expected, to get the proper name for the tabs, simply click them and grab everything after 'http://server.address/#tab_' in your address bar and use that. Be sure not to include the 'tab_' part though.
