### ISSUE TITLE
Tooltip doesn't work on tab

### ISSUE THREAD

**Issue by OllisGit** [jneilliii/OctoPrint-TabOrder#12]
The tooltip is only shown, if the pointer is excactly over the font-icon. If the pointer is in a corner of a tab, it doesn't popup.
Maybe it is a good idea to put the title-attribute to the anchor like this:

`<a href="#temp" title="My Temperature" data-toggle="tab"><i ...`

**Comment by jneilliii** [comment]
Yeah, I was thinking the same, I bound the tooltip to the icon, not the link itself.  I'll make that adjustment tonight.

**Comment by jneilliii** [comment]
This was modified in the latest 0.5.0 release.
