### ISSUE TITLE
Taborder never work for me, Yes i have clear the browser cache

### ISSUE THREAD

**Issue by ChiliApple** [jneilliii/OctoPrint-TabOrder#15]
Hy,

the taporder never works for me, since weeks, so i had unstall it. now today with the latest version ido it again, but it doesnt work. the thing is, the new ICONS works look @ screenshot, but not the TabOrder ...

thx

best Udo
![bildschirmfoto 2018-05-12 um 12 25 07](https://user-images.githubusercontent.com/38113577/39957257-4e02b31c-55f0-11e8-8063-b8f8efc7a3e0.png)

**Comment by ChiliApple** [comment]
![bildschirmfoto 2018-05-12 um 14 26 23](https://user-images.githubusercontent.com/38113577/39957263-7a5a4af6-55f0-11e8-9cd3-4e2da1d2bb34.png)

**Comment by jneilliii** [comment]
Any errors in browser console or octoprint.log? What version of octoprint and on what os? Check your config.yaml, does the appearance section update at all? If you manually update config.yaml appearance section does it rearrange the tabs?

**Comment by ChiliApple** [comment]
no, also manually update config.yaml doesnt work.


![bildschirmfoto 2018-05-12 um 18 30 29](https://user-images.githubusercontent.com/38113577/39959508-f9222260-5612-11e8-84f4-f5baebfdc98c.png)

**Comment by ChiliApple** [comment]
maybe in the Log the Warnings 
![bildschirmfoto 2018-05-12 um 18 37 08](https://user-images.githubusercontent.com/38113577/39959559-9e53bd3e-5613-11e8-8873-4236dbe3bb8a.png)

**Comment by jneilliii** [comment]
I don't think any of those error are causing the problem, as I am also getting those not found warnings.  I did just re-push 0.5.0 with the missing font files for fontawesome though, which should eliminate those warnings.  The section you are showing in the config.yaml does look right, which is the tabs saved in the plugin settings.  What I was looking for though was the section under appearance, which is what controls the tab order.  Should look something like this...
```
appearance:
  components:
    order:
      tab:
      - temperature
      - control
      - terminal
      - plugin_bedlevelvisualizer
      - plugin_youtubelive
      - timelapse
```
All this plugin does relative to tab order is write those settings to config.yaml to allow OctoPrint's built in functions to order those. I would recommend trying a restart of the OctoPrint service followed by a CTRL+F5 on the keyboard, assuming the appearance section in config.yaml looks correct.

**Comment by ChiliApple** [comment]
i have deinstall the Themeify Plugin, now it works ...

**Comment by jneilliii** [comment]
That's strange.  I don't think there is a conflict, but to verify I just installed the Themeify plugin and it is still working for me.  I bet what happened is the uninstall triggered a restart/reload process and so the updated settings in config.yaml picked up.  I'd recommend reinstalling Themeify since I don't think there is an issue there.  If there is, let me know what settings you are using in that plugin.
