### ISSUE TITLE
[Request] Include SidebarOrder-Plugin into your plugin

### ISSUE THREAD

**Issue by OllisGit** [jneilliii/OctoPrint-TabOrder#17]
Please include https://github.com/zoombahh/OctoPrint-SidebarOrder into your plugin.
Reasons:
- Your plugin is "officle" listed in octoprint-plugin repo.
- One plugin for ordering and not two

Thx, in advance
Ollli

**Comment by Dalewn** [comment]
I agree. This would be pretty neat.

Also: Would it technically be possible to move items between sidebar and main tab view?

**Comment by jneilliii** [comment]
It would not be possible to move sidebar panels to tabs without completely taking over the ui system, similar to how touchui does in the latest version.

**Comment by Dalewn** [comment]
Okay, too bad.
Thanks for the fast feedback!

**Comment by jneilliii** [comment]
Have you seen my DragonOrder plugin?  It allows for rearranging both tabs and sidebar panels, but unfortunately doesn't have the other features like icons, etc.
