### ISSUE TITLE
Not making new tabs

### ISSUE THREAD

**Issue by Lrdnykon** [jneilliii/OctoPrint-TabOrder#19]
Just installed this on a new octopi 0.15.1 instance on a pi 3 b+ and while I can reorder the 5 tabs that are there by default it wont create new tabs, the other tabs that would be there if there were more than 5 are in the drop down menu to the right.
![capture2](https://user-images.githubusercontent.com/45125285/48662395-9bae2f80-ea4f-11e8-8839-ece5ee93e2d6.JPG)
![capture3](https://user-images.githubusercontent.com/45125285/48662397-a1a41080-ea4f-11e8-80b9-dd904c07cc53.JPG)

**Comment by jneilliii** [comment]
Those tabs appear to already be added in your list. The ones that start with plugin are the additional ones. The name displayed is not the underlying name used by the plugin. For example `Cancel Objects` is the dance thing as `plugin_cancelobject`.

**Comment by Lrdnykon** [comment]
What I was trying to say was that I didn't want the drop down menu to be there. I want all the options to be under individual tabs. So if everything was the way I wanted i would have 8 separate tabs. It pops up with all separate tabs when I reload the page but then it moves the other 3 into the drop down menu. I've seen octopi videos where there are more than 5 tabs but mine wont give me that.

**Comment by jneilliii** [comment]
Gotcha. My plugin doesn't control that factor, but if you assign an icon to each of the tabs and disable label option it will allow all the tabs to be visible without collapsing I think. The videos you saw may have had a Themify hack applied.

**Comment by Lrdnykon** [comment]
Ok thanks for the quick replies
