### ISSUE TITLE
Order plugins

### ISSUE THREAD

**Issue by GekoCH** [jneilliii/OctoPrint-TabOrder#2]
hy
I tried to order the "Print History Plugin" and the "Printer Stats" plugin however I can't get it to work...

Andy

**Comment by jneilliii** [comment]
How did you enter the tab identifier for these plugins and did you press CTRL+F5 to force a refresh of the page. Plugin tab identifiers will be in the form of plugin_<plugin identifier> so for Print History it would be plugin_printhistory, see #1 for an example of this in a screenshot.
