### ISSUE TITLE
v0.5.3 makes Temperature → Offset icons disappear

### ISSUE THREAD

**Issue by xoan** [jneilliii/OctoPrint-TabOrder#25]
![captura de pantalla_2019-01-22_17-51-24](https://user-images.githubusercontent.com/288246/51551693-420f1a80-1e6f-11e9-8358-dd4c83be63c0.png)

**Comment by jneilliii** [comment]
I'm not seeing the same thing in my install of version 0.5.3.  It actually should have fixed this issue introduced with version 0.5.2. 

![image](https://user-images.githubusercontent.com/5249455/51795762-fcc45300-21b6-11e9-981d-0b9c5b5a071c.png)

**Comment by jneilliii** [comment]
Do you have touchui plugin installed? I just noticed on my other pi that has that installed I'm seeing this button issue,.

**Comment by xoan** [comment]
My apologies. I have Touch UI installed and the issue doesn't appear when Touch UI is disabled.
