### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by jkkato** [jneilliii/OctoPrint-TabOrder#27]
I am trying to set up the Tab Order. When I add icons only a square shows up. I even copied the text in the example photos and did the <CTRL> + F5 refresh. I can turn the label on and off and the tool tip and color work.

![Tab Order](https://user-images.githubusercontent.com/26161239/66283883-1a83a500-e87a-11e9-8b69-5d6c73367784.png)
![Tab Order Settings](https://user-images.githubusercontent.com/26161239/66283934-5e76aa00-e87a-11e9-88cc-bb348d2b588e.png)

**Comment by jkkato** [comment]
I should add that this is the same for both my printers...

![Tab Order Select Mini](https://user-images.githubusercontent.com/26161239/66284122-40f61000-e87b-11e9-9702-a0fa1420b9e3.png)

**Comment by jneilliii** [comment]
Per the changelog, 

```
Updated to fontawesom 5.6.3. As a result, some icons may become broken. In order to handle the new solid versus branded icons the base icon class (fas or fab) must also be included in the icon field.
```

**Comment by jkkato** [comment]
I did see that changelog, and added the three letters, but it did not work either. One problem is that the instructions does not say how to add these letters to the icon field, so I guessed.

**Comment by jkkato** [comment]
I am not at the computer right now... I will be home later.

**Comment by jneilliii** [comment]
Here's a quick example.

![image](https://user-images.githubusercontent.com/5249455/66337463-2f5d4880-e90d-11e9-823b-3b0159ff602f.png)

**Comment by jkkato** [comment]
OK. Thanks. I will try it when I get home. I had put something like "fas-thermometer".

**Comment by jkkato** [comment]
Working now. Thanks.
