### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by leoheck** [jneilliii/OctoPrint-TabOrder#28]
Hi, where I can find a list of icons?
I saw many pictures with icons, but not a list of them. 

Can you please, share a link with this list or add it in README.md?

Or even better, why this plugin does not come with icons filled by default?
I mean, if the user wants to change the text by and icon it clicks a checkbox, to enable an input field with a default icon there that can be changed too.

What do you think?

**Comment by jneilliii** [comment]
Pretty sure there's a link on the readme to fontawesome as well as clicking the info icon.

**Comment by leoheck** [comment]
The info icon was good but I had to take some time to understand the syntax, it is not straight forward especially if you don't know what to do. A note on readme will be good. I was not able to find the info on the readme. If it is under changelog it won't work since I was looking for info about the usage, not the changelog.

Well, this is my suggestion to improve it. Have a nice day.

**Comment by jneilliii** [comment]
Understood.  I was trying to implement an icon selector option but haven't had much time to work on it.

**Comment by jneilliii** [comment]
If you don't mind testing for me that would be great.  You can install a test version by using the url below in plugin manager.  Let me know how it works out.

https://github.com/jneilliii/OctoPrint-TabOrder/archive/0.5.5.zip

**Comment by leoheck** [comment]
I am doing it right now.

**Comment by leoheck** [comment]
It looks promising dude!
![image](https://user-images.githubusercontent.com/1277920/68065020-02306a00-fd02-11e9-9df0-fa0d2f0433e8.png)

**Comment by leoheck** [comment]
I was able to replace all of my icons. I was using this version that starts with `fa` and they were replaced by something that starts with `fas`
I don't know what this tag does but everything was set just easy. Dude, this is awesome.
![image](https://user-images.githubusercontent.com/1277920/68065068-78cd6780-fd02-11e9-9c83-d565464cf82f.png)

**Comment by jneilliii** [comment]
Great, glad it works as expected.  I'll update the version and push an official release.

**Comment by leoheck** [comment]
Good. Thanks.
--
Leandro Heck
