### ISSUE TITLE
Cannot move between hidden and assigned

### ISSUE THREAD

**Issue by tablatronix** [jneilliii/OctoPrint-TabOrder#34]
Maybe I missed it, but the only way to move between the 2 is to delete it and lose all settings for a tab..

**Comment by jneilliii** [comment]
You should be able to drag from one to the other.

**Comment by tablatronix** [comment]
Ill try again and see whats going on

**Comment by jneilliii** [comment]
Ok, I see a situation where if there isn't anything in the hidden tabs section you don't have a place to drop the item from the other list. You can press the delete button on one of those higher up and then use the right [+] button to add it to the hidden section, and then you can drag others into the same area.

**Comment by tablatronix** [comment]
ahh, makes sense yeah there was no way to drop there as I had no items there, no drop target

**Comment by jneilliii** [comment]
Just released update to set the min-height to allow dragging into empty lists.
