### ISSUE TITLE
Not changing tab order with additional tab plugins

### ISSUE THREAD

**Issue by Llama-Trauma** [jneilliii/OctoPrint-TabOrder#4]
Hey there!

I added the plugin, but there were not instructions on how to manage the "additional" tabs I have from new plugin such as a dedicated webcam tab, and the STL Viewer. 

Based on contextual clues, I saw that spaces and capital letters were ignored. I used the + Add Tab Identifier button to add "webcam" and "stlviewer" but that did not enable movement of those tabs with the included arrows in settings. Additionally, I was unable to move any of my tabs using this plugin. I had not tested it prior to installing other plugins, so additional testing is needed, but core functionality was missing either way. 

Appreciate any support or a new release with notes on how to add new plugin tabs please!

**Comment by jneilliii** [comment]
Prepend plugin identifiers with plugin_ for example plugin_webcamtab.

**Comment by Llama-Trauma** [comment]
![image](https://user-images.githubusercontent.com/32855921/35655760-559a93a2-06a8-11e8-82e1-45f62b6babf9.png)

![image](https://user-images.githubusercontent.com/32855921/35655794-8df499dc-06a8-11e8-906f-596f56ea01b5.png)

I've just tried your suggestion, saved, refreshed, and even restarted Octoprint - the webcam tab won't move. The "Terminal" tab (just off-screen in the first image) also did not move accordingly. 

Any other tips or tricks?

**Comment by jneilliii** [comment]
When you refreshed, did you use ctrl+f5 to clear the browser cache.

**Comment by jneilliii** [comment]
And you have the identifier wrong. It should be plugin_webcamtab. Look at the read me for a better description of getting that identifier.

**Comment by Llama-Trauma** [comment]
Yes, I even manually cleared cache.

**Comment by Llama-Trauma** [comment]
That worked, thanks for the help! (Sorry for being n00b, and not reading
enough)

**Comment by jneilliii** [comment]
No, problem.  I just added the information to the readme a couple of days ago to try and clear up some of the confusion.  If you aren't a plugin developer you may not even know about plugin identifiers.
