### ISSUE TITLE
[BUG] interaction with TouchUI

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jneilliii/OctoPrint-TabOrder#41]
currently there is an unexpected interaction with 
https://github.com/BillyBlaze/OctoPrint-TouchUI
when TabOrder icons also show up next to TouchUI icons

**Comment by jneilliii** [comment]
I think I got this fixed and staged for my next version release. If you want to test and verify that would be great. Copy/Paste the URL below into plugin manager > get more > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-TabOrder/archive/0.5.12rc2.zip
```
