### ISSUE TITLE
[FR] optional icon color

### ISSUE THREAD

**Issue by SirFlip** [jneilliii/OctoPrint-TabOrder#42]
It would be usefull to make the Color optional, so it can be inherited.
Then the color changes with the text and wheather the tab is currently selected or not.
 
It's a great plugin nevertheless. Thank you

**Comment by jneilliii** [comment]
Yeah, I didn't think of that since I was using the color input type, apparently their is no option for inherit. I think what I can do is split that one field up into two, and allow for manually adding the color code, which would allow removing it completely, nice idea.

**Comment by jneilliii** [comment]
I've got the changes staged for the next release, but am trying to work out a reload issue with tab order settings changes prior to official release.
