### ISSUE TITLE
Tab Order has no effect

### ISSUE THREAD

**Issue by ranger81** [jneilliii/OctoPrint-TabOrder#44]
Just installed your plugin. Setting tab icons and hide tabs does work, but the sort order for the assigned tabs has no effect on my octoprint installation. I rearrange the tabs in the plugin settings, but even though I press "Save" is not properly done. Any ideas?
Thanks

**Comment by jneilliii** [comment]
Are you forcing a refresh? Press either ctrl+F5 or shift+F5 in your keyboard to force a cache reload.

**Comment by ranger81** [comment]
Yes, I did even clear the browser cache. The tab icon is changed properly but not the tab order.
Is there any incompatibility with Themeify?

Please see this screenshots:
![tab order](https://user-images.githubusercontent.com/3425811/89127175-ff121680-d4eb-11ea-9afa-71d548a08907.png)

![tab order](https://user-images.githubusercontent.com/3425811/89127298-c161bd80-d4ec-11ea-9be2-e8bce857ad0b.png)

**Comment by jneilliii** [comment]
Can you please press F12 and look for errors in the developer console? It's working fine over here in Chrome. What browser are you using? I notice you are also using Themeify. Do you have the tab icon setting enabled in that plugin, could potentially cause conflict.

**Comment by ranger81** [comment]
There is one error in the console, see attachment. I'm using Safari on Mac.
I have now also tried Chrome on Windows, unfortunately the same issue.
The Tab icon feature of Themeify is disabled. 

![console](https://user-images.githubusercontent.com/3425811/89127480-0b976e80-d4ee-11ea-88d7-89e233a17758.png)

I have installed the following plugins:
Bed Visualizer (0.1.14)
BetterHeaterTimeout (1.2.0)
Custom Control Editor (0.2.2)
Detailed Progress (0.2.5)
EEPROM Marlin Editor Plugin (1.2.1)
Navbar Temperature Plugin (0.14)
OctoPod Plugin (0.2.6
PrintTimeGenius Plugin (2.2.5)
Simple Emergency Stop (1.0.1)
Tab Order (0.5.9)
Themeify (1.2.2)
Webcam Tab (0.1.2)

OctoPrint 1.4.0 running on OctoPi 0.16.0

**Comment by jneilliii** [comment]
Ok, the error there is not related to my plugin but it could be breaking my plugin from being able to do what it does. Not sure what plugin that might be causing that though.

**Comment by jneilliii** [comment]
One thing to check would be to SSH to your pi and run the following command to read through the config.yaml and verify the appearance > order > tab section is getting updated.

```
nano ~/.octoprint/config.yaml
```

**Comment by ranger81** [comment]
The config.yaml file content matches my settings in the UI.
![yaml](https://user-images.githubusercontent.com/3425811/89127987-70ed5e80-d4f2-11ea-929d-d0eadc1ed5c1.png)

After my print is done I'm going to disable some other plugins to see, if I can find one which causes the issue.

**Comment by ranger81** [comment]
The error in the console was caused by the PrintTimeGenius plugin. Disabling the plugin did not solve my issue. However, once Octopi was restarted (because of disabling of the plugin), the tab order was correct. It seems that I need to restart the OctoPi to "refresh" the tab order, a simple force reload does not work on my installation, don't know why, but I somehow "solved" it. Thanks for your support!
