### ISSUE TITLE
Tabs do not reorder - Octoprint 1.3.6

### ISSUE THREAD

**Issue by dougcooper** [jneilliii/OctoPrint-TabOrder#5]
I've tried different variants of the tab identifiers but cannot get them to reorder after reloading the webpage. For example if the webpage is https://octopi.local/#temp, I try to use "temp" as the identifier.

**Comment by jneilliii** [comment]
Are you reloading by pressing ctrl+f5?  If you don't reload that way it will automatically load from cache.

**Comment by dougcooper** [comment]
Shame on me for using a Mac ;) I could not get this to work in safari whatsoever event after trying to manually clear the cache and then reload. In chrome however it works using: command+shift+R.
