### ISSUE TITLE
Plotly Temp Graph tab is not showing in the correct place

### ISSUE THREAD

**Issue by Mox2488** [jneilliii/OctoPrint-TabOrder#53]
Hello, I am now using the Plotly Temp Graph (0.1.3) plugin.
But this tab is not showing in the right place. Would like to display it as the 2nd, but it is always at the end.

Octopi 0.18.0
Octoprint 1.7.2
Python 3.7.3

![image](https://user-images.githubusercontent.com/73469539/140653819-18b8c443-d874-4122-85f0-8aabac40ad52.png)

![image](https://user-images.githubusercontent.com/73469539/140653844-fb6edbcd-1c3a-4a6e-9ea7-a4eae532e87e.png)

Thank you very much

**Comment by jneilliii** [comment]
Try disabling the plotlytempgraph plugin and put the default temperature tab where you want it and then reenable the tab order plugin and see if that helps.
