### ISSUE TITLE
Can not change the order

### ISSUE THREAD

**Issue by Guitarans** [jneilliii/OctoPrint-TabOrder#54]
running the latest version of octoprint.
My tab order looks like this..
![image](https://user-images.githubusercontent.com/19931810/142696940-36a8aab6-b279-475f-9382-cbe582b07a44.png)

it dosnt matter if i change the order in the settings..
The icons work.. even if i change the order, the tabs dosnt change possition

**Comment by jneilliii** [comment]
The tabs won't re-order until you do a forced refresh (shift + f5 typically) of the browser after saving.

**Comment by Guitarans** [comment]
Great, It worked.. ( the shift + F5 with my usb keyboard, But not with my laptop keyboard ) Anyway thanks for the quick reply...
i just thought something were off, since i didnt have that many options in the settings for the plugin.. Great work!!

**Comment by jneilliii** [comment]
Cool and thanks for the tip.

**Comment by synthead** [comment]
I'm seeing the same problem.  This is with Octoprint 1.10.3, Tab Order 0.5.12.  I have attempted a Ctrl+Shift+R in Firefox, but the tabs remain in the same locations as before.

I cannot reopen this issue, so I filed a duplicate here: https://github.com/jneilliii/OctoPrint-TabOrder/issues/58
