### ISSUE TITLE
How to backup/import/export settings

### ISSUE THREAD

**Issue by TylonHH** [jneilliii/OctoPrint-TabOrder#55]
Hi,
just a quick question and maybe a feature request. As I have multiple printers with octoprint I'd like to use the same settings on every front-end. I guess there is a quick workaround where I can copy some files via SSH or FTP. But wich ones?
Best regards

**Comment by jneilliii** [comment]
the actual settings are stored in /home/pi/.octoprint/config.yaml under the section plugins > taborder.
