### ISSUE TITLE
Tab name references use specific keywords

### ISSUE THREAD

**Issue by dougcooper** [jneilliii/OctoPrint-TabOrder#6]
I first attempted to use the URL fragment as the keyword, but that was not correct. Here are the specific keywords to use (as examples):
temperature (not "temp")
gcodeviewer (not "gcode")
terminal (not "term")
plugin_webcamtab (without the "tab_")

**Comment by jneilliii** [comment]
You are correct, the default tabs are hard coded and don't follow the same hashtag trick you can use for the plugins.  What you figured out is correct.  I'll update the readme to list the default tabs.

**Comment by jneilliii** [comment]
Just realized, the Readme does show the screenshot of the default tabs, as you listed them and includes a section on how to identify plugin tabs for use in this plugin.
